#!/usr/bin/env python3
import mwapi
import sys
import toolforge

user_agent = toolforge.set_user_agent(tool='purge-other-usages',
                                      email='lucas.werkmeister@wikimedia.de')


try:
    wiki_domain = sys.argv[1]
    entity_id_offset = sys.argv[2]
    page_id_offset = int(sys.argv[3])
except IndexError:
    print(f'''
Usage: {sys.argv[0]} DOMAIN ENTITY_ID PAGE_ID

    DOMAIN: e.g. en.wikipedia.org
    ENTITY_ID: e.g. Q42; set to '' when not continuing
    PAGE_ID: e.g. 1234; set to 0 when not continuing
'''.strip(), file=sys.stderr)
    sys.exit(1)

session = mwapi.Session(host=f'https://{wiki_domain}',
                        user_agent=user_agent)

wiki_db = session.get(action='query',
                      meta='siteinfo')['query']['general']['wikiid']

connection = toolforge.connect(wiki_db)

with connection.cursor() as cursor:
    while True:
        cursor.execute('''SELECT eu_entity_id, eu_page_id
                          FROM wbc_entity_usage
                          WHERE eu_aspect = 'O'
                          AND (eu_entity_id > %s
                           OR (eu_entity_id = %s
                            AND eu_page_id > %s))
                          ORDER BY eu_entity_id ASC, eu_page_id ASC
                          LIMIT 500''',
                       (entity_id_offset, entity_id_offset, page_id_offset))
        rows = [(entity_id.decode('utf8'), page_id) for entity_id, page_id in cursor.fetchall()]
        entity_id_offset, page_id_offset = rows[-1]
        page_ids = list(set(page_id for _, page_id in rows))

        for chunk in [page_ids[i:i+50] for i in range(0, len(page_ids), 50)]:
            session.post(action='purge',
                         pageids=chunk)

        print(f'Processed up to {entity_id_offset}, {page_id_offset}.')
        break
